byCedric/use-expo

packages/permissions/src/use-permissions.ts
Including lodash just for array casting is an overkill.
=> Replace lodash array casting with native

packages/brightness/package.json, packages/brightness/tsconfig.build.json, packages/brightness/tsconfig.json, packages/permissions/package.json, packages/permissions/tsconfig.build.json, packages/permissions/tsconfig.json, packages/sensors/package.json, packages/sensors/tsconfig.build.json, packages/sensors/tsconfig.json
When building, it's being excluded to only build the source files. It's a dirty fix, but one that works.
=> fix: add tests to tsconfig for development

README.md, packages/brightness/package-lock.json, packages/permissions/package-lock.json, packages/screen-orientation/README.md, packages/screen-orientation/docs/use-screen-orientation-lock.md, packages/screen-orientation/package-lock.json, packages/screen-orientation/src/index.ts, packages/screen-orientation/src/use-screen-orientation-lock.ts, packages/screen-orientation/tests/use-screen-orientation-lock.test.ts, packages/sensors/package-lock.json
This adds a basic screen orientation lock hook, based on the [`useKeepAwake` hook from Expo](https://github.com/expo/expo/blob/master/packages/expo-keep-awake/src/index.ts#L40-L45).
=> Add first draft of screen orientation lock hook

example/.eslintrc.json, example/package-lock.json, example/package.json
This adds the two ESLint hooks rules to the example project. It's a basic security to double check if all hooks are implemented properly.
=> chore(example): add react hooks eslint rules

packages/brightness/package.json, packages/font/package.json, packages/permissions/package.json, packages/sensors/package.json
This fixes the warning about peer dependencies not installed for newer expo `6.x.x` modules.
=> fix: allow latest expo modules as peer dependencies

package-lock.json, packages/brightness/package.json, packages/font/package.json, packages/permissions/package.json, packages/screen-orientation/package.json, packages/sensors/package.json
Let's upgrade to the newer `6.x.x` expo modules.
=> refactor: update expo modules to newer v6

.github/workflows/example-ci.yml, .github/workflows/packages-ci.yml
Commitlint was missing from the new github workflows.
=> fix: add missing commitlint to github workflow

.github/workflows/example-ci.yml, example/.eslintrc.json, example/commitlint.config.js, example/package-lock.json, example/package.json, example/src/atoms/measurement.tsx, example/src/providers/theme.tsx
This separates example app's eslint from the monorepo.
=> refactor(example): decouple eslint from monorepo

.github/workflows/example-publish.yml
New Expo GitHub Action v4 is out, let's use that one.
=> refactor(example): update expo action version to v4

.github/workflows/example-publish.yml
This adds some caching to the Expo CLI, and should speed up our builds.
=> refactor: use latest expo github action with cache

NEW_PEDOMETER_HISTORY.ats, packages/brightness/src/use-system-brightness-mode.ts, packages/brightness/tests/use-system-brightness-mode.test.ts
This fixes the hook dependency warning for the brightness hooks.
=> fix(brightness): fetch brighness mode after new props

packages/screen-orientation/src/use-screen-orientation.ts, packages/screen-orientation/tests/use-screen-orientation-lock.test.ts, packages/screen-orientation/tests/use-screen-orientation.test.ts
This improves the screen orientation hook by adding:
- `getScreenOrientation` callback, to manually update the orientation
- `listen` option, to disable orientation changes
It also restructures the screen orientation hook's tests, for more readability.
=> feat(screen-orientation): add manual get callback and listen option

example/src/molecules/sensors/use-pedometer.tsx, packages/sensors/src/use-accelerometer.ts, packages/sensors/src/use-barometer.ts, packages/sensors/src/use-device-motion.ts, packages/sensors/src/use-gyroscope.ts, packages/sensors/src/use-magnetometer-uncalibrated.ts, packages/sensors/src/use-magnetometer.ts, packages/sensors/src/use-pedometer-history.ts, packages/sensors/src/use-pedometer.ts, packages/sensors/tests/use-accelerometer.test.ts, packages/sensors/tests/use-barometer.test.ts, packages/sensors/tests/use-device-motion.test.ts, packages/sensors/tests/use-gyroscope.test.ts, packages/sensors/tests/use-magnetometer-uncalibrated.test.ts, packages/sensors/tests/use-magnetometer.test.ts, packages/sensors/tests/use-pedometer-history.test.ts, packages/sensors/tests/use-pedometer.test.ts
This rewrites the tests for sensor hooks to keep it maintainable and test for misusage of variable dependencies. It should behave a bit better when changing the properties of the hooks.
=> refactor(sensors): rework tests and properly use dependencies

example/src/molecules/sensors/index.ts, example/src/molecules/sensors/use-pedometer-history.tsx, example/src/molecules/sensors/use-pedometer.tsx
Splitting them out shows developers better that these are separate hooks. You can either track live results, or fetch data that's already there. (or both, if you combine them 😄)
=> refactor(example): separate history and live pedometer examples

example/src/molecules/brightness/use-brightness.tsx, example/src/molecules/brightness/use-system-brightness.tsx, packages/brightness/src/use-brightness.ts, packages/brightness/src/use-system-brightness-mode.ts, packages/brightness/src/use-system-brightness.ts, packages/brightness/tests/use-brightness.test.ts, packages/brightness/tests/use-system-brightness-mode.test.ts, packages/brightness/tests/use-system-brightness.test.ts
This improves the DX, test coverage, and performance of the brightness hooks.
=> refactor(brightness): reuse callbacks and docs to hooks

packages/battery/src/use-battery-state.ts
It matches the new brightness annotation, and should mark the enum names a bit better.
=> docs(battery): use code annotation in state enum

example/src/atoms/missing-permissions.tsx, example/src/molecules/permissions/use-permissions.tsx, packages/permissions/src/use-permissions.ts, packages/permissions/tests/use-permissions.test.ts
This should improve DX with docs and performance by not-initiating new ask/get callbacks for single permissions.
=> refactor(permissions): add docs and update rerendering performance

.eslintrc.js, packages/battery/src/use-battery-level.ts, packages/battery/src/use-battery-low-power-mode.ts, packages/battery/src/use-battery-state.ts, packages/battery/src/use-battery.ts, packages/brightness/src/use-brightness.ts, packages/brightness/src/use-system-brightness-mode.ts, packages/brightness/src/use-system-brightness.ts, packages/font/src/use-fonts.ts, packages/permissions/src/use-permissions.ts, packages/screen-orientation/src/use-screen-orientation-lock.ts, packages/screen-orientation/src/use-screen-orientation.ts, packages/sensors/src/use-accelerometer.ts, packages/sensors/src/use-barometer.ts, packages/sensors/src/use-device-motion.ts, packages/sensors/src/use-gyroscope.ts, packages/sensors/src/use-magnetometer-uncalibrated.ts, packages/sensors/src/use-magnetometer.ts, packages/sensors/src/use-pedometer-history.ts, packages/sensors/src/use-pedometer.ts
Its now visible when hovering over the hook in e.g. vscode. That makes it a bit understable.
=> refactor: use inline return types for better visibility

packages/battery/src/use-battery-level.ts, packages/battery/src/use-battery-low-power-mode.ts, packages/battery/src/use-battery-state.ts, packages/battery/src/use-battery.ts, packages/battery/tests/use-battery-level.test.ts, packages/battery/tests/use-battery-low-power-mode.test.ts, packages/battery/tests/use-battery-state.test.ts, packages/battery/tests/use-battery.test.ts
This should make the battery hooks a bit faster, especially when listening for changes.
=> fix(battery): unify tests and fix callback reuse

README.md, example/README.md, example/app.json, packages/battery/README.md, packages/battery/docs/use-battery-level.md, packages/battery/docs/use-battery-low-power-mode.md, packages/battery/docs/use-battery-state.md, packages/battery/docs/use-battery.md, packages/brightness/README.md, packages/brightness/docs/use-brightness.md, packages/brightness/docs/use-system-brightness-mode.md, packages/brightness/docs/use-system-brightness.md, packages/font/README.md, packages/font/docs/use-fonts.md, packages/permissions/README.md, packages/permissions/docs/use-permissions.md, packages/screen-orientation/README.md, packages/screen-orientation/docs/use-screen-orientation-lock.md, packages/screen-orientation/docs/use-screen-orientation.md, packages/sensors/README.md, packages/sensors/docs/use-accelerometer.md, packages/sensors/docs/use-barometer.md, packages/sensors/docs/use-device-motion.md, packages/sensors/docs/use-gyroscope.md, packages/sensors/docs/use-magnetometer.md, packages/sensors/docs/use-pedometer-history.md, packages/sensors/docs/use-pedometer.md, packages/use-expo/README.md
This should help:
- navigating back and forth
- copying working examples without additional code
- understanding the API sections
- links to GH actions
- info about `use-expo` vs `@use-expo/*`
=> docs: simplify and reformat all documentation

packages/font/src/use-fonts.ts, packages/font/tests/use-fonts.test.ts
=> fix(font): avoid render loop when using inline fontmaps

example/package.json, example/src/molecules/font/use-fonts.tsx, yarn.lock
Updates some wrong dependency updates in the example, and a minor update for the fonts example.
=> refactor(example): update fonts example with inline fontmap

.github/workflows/preview.yml
It won't work for branches pushed to an ignored repository. 😅
=> chore: remove preview filtering from the workflow
