README.md, packages/brightness/README.md, packages/brightness/babel.config.js, packages/brightness/docs/use-brightness.md, packages/brightness/jest.config.js, packages/brightness/package-lock.json, packages/brightness/package.json, packages/brightness/src/index.ts, packages/brightness/src/use-brightness.ts, packages/brightness/tests/use-brightness.test.ts, packages/brightness/tsconfig.json
Adds the first brightness hook.
=> feat(brightness): add first draft of use brightness hook

README.md, packages/brightness/README.md, packages/brightness/docs/use-brightness.md, packages/brightness/docs/use-system-brightness.md, packages/brightness/src/index.ts, packages/brightness/src/use-system-brightness.ts, packages/brightness/tests/use-system-brightness.test.ts
Adds the system brightness with an example including permissions.
=> feat(brightness): add system brightness hook

README.md, packages/brightness/README.md, packages/brightness/docs/use-system-brightness-mode.md, packages/brightness/src/index.ts, packages/brightness/src/use-system-brightness-mode.ts, packages/brightness/tests/use-system-brightness-mode.test.ts
Adds the system brightness mode hook.
Although it's not really documented, it's working! You can basically set it to either manual or automatic. But it's a highly experimental feature.
=> feat(brightness): add system brightness mode hook

README.md, packages/permissions/package-lock.json, packages/screen-orientation/README.md, packages/screen-orientation/babel.config.js, packages/screen-orientation/docs/use-screen-orientation.md, packages/screen-orientation/jest.config.js, packages/screen-orientation/package-lock.json, packages/screen-orientation/package.json, packages/screen-orientation/src/index.ts, packages/screen-orientation/src/use-screen-orientation.ts, packages/screen-orientation/tests/use-screen-orientation.test.ts, packages/screen-orientation/tsconfig.build.json, packages/screen-orientation/tsconfig.json, packages/sensors/package-lock.json, packages/use-expo/package-lock.json, packages/use-expo/package.json, packages/use-expo/src/index.ts
Adds a simple screen orientation hook, other hooks to add related to screen orientation: `useScreenOrientationLock` and the platform- equivalents.
=> Add first draft of screen orientation hooks

packages/sensors/src/index.ts
=> Export pedometer history hook

example/package-lock.json, example/package.json, example/src/molecules/overview.tsx, example/src/molecules/screen-orientation/index.ts, example/src/molecules/screen-orientation/use-screen-orientation-lock.tsx, example/src/providers/navigation.tsx
There should be an example for everything right? 😁
=> Add screen orientation lock example

.github/main.workflow
New CLI is out and the Expo GitHub Actions are updated, let's use that one 😄🚀
=> Upgrade to expo actions v3

example/package-lock.json, example/package.json, package-lock.json, package.json, packages/brightness/package-lock.json, packages/brightness/package.json, packages/font/package-lock.json, packages/permissions/package-lock.json, packages/permissions/package.json, packages/screen-orientation/package-lock.json, packages/sensors/package-lock.json, packages/sensors/package.json, packages/use-expo/package-lock.json, packages/use-expo/package.json
This should fix some Lodash audit warnings.
=> refactor: upgrade all dependencies to fix audit warnings

example/package-lock.json, example/package.json
This was missing for React Navigation.
=> fix(example): add missing dependencies for react navigation

.gitignore, package-lock.json, package.json, packages/brightness/package.json, packages/brightness/tsconfig.build.json, packages/brightness/tsconfig.json, packages/font/package.json, packages/font/tsconfig.build.json, packages/font/tsconfig.json, packages/permissions/package.json, packages/permissions/tsconfig.build.json, packages/permissions/tsconfig.json, packages/screen-orientation/package.json, packages/screen-orientation/tsconfig.build.json, packages/screen-orientation/tsconfig.json, packages/sensors/package.json, packages/sensors/tsconfig.build.json, packages/sensors/tsconfig.json, packages/use-expo/package.json, packages/use-expo/tsconfig.json, tsconfig.json, tsconfig.shared.json
Last one of the root-refactors! 😄
=> refactor: move typescript to root for improved performance

example/app.json, example/package-lock.json, example/package.json, example/src/molecules/overview.tsx, example/src/providers/navigation.tsx
Upgrade to the latest Expo SDK (35).
=> refactor(example): upgrade dependencies and expo to sdk 35

package-lock.json, packages/battery/package.json, packages/brightness/package.json, packages/font/package.json, packages/permissions/package.json, packages/screen-orientation/package.json, packages/sensors/package.json
Fixes the hoisting warnings related to `@types/react`.
=> fix: use same react types for hoisting

example/package-lock.json, example/package.json, example/src/molecules/battery/use-battery-level.tsx, example/src/molecules/battery/use-battery-low-power-mode.tsx, example/src/molecules/battery/use-battery-state.tsx, example/src/molecules/battery/use-battery.tsx
=> chore(example): upgrade to use expo 0.10.0

example/package-lock.json, example/package.json
Upgrade to the latest version, _with built files_...
=> chore(example): upgrade to use expo 0.10.1

packages/permissions/src/use-permissions.ts, packages/permissions/tests/use-permissions.test.ts
Fixes the dependencies of the permissions handlers.
=> fix(permissions): use callbacks and dependencies

packages/battery/src/use-battery-level.ts, packages/battery/src/use-battery-low-power-mode.ts, packages/battery/src/use-battery-state.ts, packages/battery/src/use-battery.ts
Should help with some DX when working with these hooks.
=> docs(battery): add inline info about the hooks

packages/screen-orientation/src/use-screen-orientation-lock.ts, packages/screen-orientation/src/use-screen-orientation.ts
Improve DX with additional comments for the screen orientation hooks.
=> docs(screen-orientation): add information about the hooks

packages/sensors/src/use-accelerometer.ts, packages/sensors/src/use-barometer.ts, packages/sensors/src/use-device-motion.ts, packages/sensors/src/use-gyroscope.ts, packages/sensors/src/use-magnetometer-uncalibrated.ts, packages/sensors/src/use-magnetometer.ts, packages/sensors/src/use-pedometer-history.ts, packages/sensors/src/use-pedometer.ts, packages/sensors/tests/use-pedometer-history.test.ts
Improve DX with information for the sensors.
=> docs(sensors): add information about the hooks

.github/workflows/preview.yml
Should help getting PR's merged asap 😄
=> chore: add preview workflow with comments on pr

tsconfig.json
Expo/Metro will minify it, but the DX you get out of is worth keeping it here.
=> chore: keep comments in built typescript files

packages/web-browser/CHANGELOG.md, packages/web-browser/README.md, packages/web-browser/docs/use-browsers.md, packages/web-browser/docs/use-warm-browser.md, packages/web-browser/package.json, packages/web-browser/src/index.ts, packages/web-browser/src/use-browsers.ts, packages/web-browser/src/use-warm-browser.ts, packages/web-browser/tsconfig.json
Feel free to modify this however you see fit.
=> Created web browser hooks

README.md, example/package.json, example/src/molecules/overview.tsx, example/src/molecules/web-browser/index.ts, example/src/molecules/web-browser/use-browsers.tsx, example/src/providers/assets.tsx, example/src/providers/urls.tsx, packages/use-expo/package.json, packages/use-expo/src/index.ts, packages/use-expo/tsconfig.json, packages/web-browser/docs/use-browsers.md, packages/web-browser/docs/use-warm-browser.md, packages/web-browser/package.json, packages/web-browser/src/index.ts, packages/web-browser/src/use-browsers.ts, packages/web-browser/src/use-warm-browser.ts, packages/web-browser/tests/use-browsers.test.ts, packages/web-browser/tests/use-warm-browser.test.ts, yarn.lock
Fixes CI for web browser hooks
=> fix(web-browser): add tests, fix lint errors and finish docs

example/src/molecules/screen-orientation/use-screen-orientation-lock.tsx
Should make it a bit more understandable 😄
=> fix(example): use orientation lock names in example

packages/application/CHANGELOG.md, packages/application/README.md, packages/application/docs/use-application-android-install-referrer.md, packages/application/docs/use-application-android-last-update-time.md, packages/application/docs/use-application-install-time.md, packages/application/docs/use-application-ios-id-for-vendor.md, packages/application/package.json, packages/application/src/index.ts, packages/application/src/use-application-android-install-referrer.ts, packages/application/src/use-application-android-last-update-time.ts, packages/application/src/use-application-install-time.ts, packages/application/src/use-application-ios-id-for-vendor.ts, packages/application/tests/use-application-android-install-referrer.test.ts, packages/application/tests/use-application-android-last-update-time.test.ts, packages/application/tests/use-application-install-time.test.ts, packages/application/tests/use-application-ios-id-for-vendor.test.ts, packages/application/tsconfig.json, yarn.lock
#2 Application Hooks
Not sure what to do with the **package.json**, **CHANGELOG.md** and **README.md** files. Also not yet added to the `use-expo` package. If you can explain what to do to with that files and package, I'm happy to make the required changes.
=> Application hooks

lerna.json, packages/application/package.json, packages/use-expo/package.json, packages/use-expo/src/index.ts
=> chore: version all packages independently

packages/application/README.md, packages/battery/README.md, packages/brightness/README.md, packages/font/README.md, packages/permissions/README.md, packages/screen-orientation/README.md, packages/sensors/README.md, packages/use-expo/README.md, packages/web-browser/README.md
=> docs: use npm version and link to changelog

example/src/molecules/application/index.ts, example/src/molecules/application/use-application-android-install-referrer.tsx, example/src/molecules/application/use-application-android-last-update-time.tsx, example/src/molecules/application/use-application-install-time.tsx, example/src/molecules/application/use-application-ios-id-for-vendor.tsx, example/src/molecules/overview.tsx, example/src/providers/urls.tsx
Useful for others to quickly check them out 😄
=> feat(example): add application hook examples

example/src/molecules/overview.tsx, example/src/molecules/store-review/index.ts, example/src/molecules/store-review/use-store-review-has-action.tsx, example/src/molecules/store-review/use-store-review-is-available.tsx, example/src/molecules/store-review/use-store-review-request.tsx, example/src/providers/urls.tsx, packages/store-review/README.md, packages/store-review/docs/use-store-review-has-action.md, packages/store-review/docs/use-store-review-is-available.md, packages/store-review/docs/use-store-review-request.md, packages/store-review/package.json, packages/store-review/src/index.ts, packages/store-review/src/use-store-review-has-action.ts, packages/store-review/src/use-store-review-is-available.ts, packages/store-review/src/use-store-review-request.ts, packages/store-review/tests/use-store-review-has-action.test.ts, packages/store-review/tests/use-store-review-is-available.test.ts, packages/store-review/tests/use-store-review-request.test.ts, packages/store-review/tsconfig.json, yarn.lock
#2 StoreReview hooks
I think I've done most part considering the documentation and examples. But if anything is missing I would like to hear 🙂
=> StoreReview hooks

.github/workflows/preview.yml
This tests the performance of the new `EXPO_USE_DEV_SERVER` 😄
=> chore: use new metro server and speed up preview

.github/workflows/example-release.yml, .github/workflows/packages.yml, .github/workflows/preview.yml
Speed up the actions for packages, previews, and publishes.
=> chore: implement cache and speed up all actions

.github/workflows/packages.yml, .prettierrc, example/src/molecules/brightness/use-brightness.tsx, example/src/molecules/brightness/use-system-brightness.tsx
Fixes the current warnings from the example app.
=> fix: example lint warnings in brightness

.github/workflows/example-release.yml, .github/workflows/preview.yml
Replace username and password auth with token.
Mostly to test the new feature, it will be available soon.
=> chore: use token when publishing new version
